apiVersion: v1
kind: Secret
metadata:
  name: smap-analytics-secret
  namespace: smap
  labels:
    app: smap-analytngine
type: Opaque
stringData:
  # Database credentials
  DATABASE_URL: "postgresql+asyncpg://smap_owner:smap_owner%4021042004@172.16.19.114:5432/smap-project"
  DATABASE_URL_SYNC: "postgresql://smap_owner:smap_owner%4021042004@172.16.19.114:5432/smap-project"

  # RabbitMQ credentials
  RABBITMQ_URL: "amqp://smap:hcmut@172.16.19.112:5672/%2f"

  # MinIO credentials
  MINIO_ENDPOINT: "http://172.16.19.115:9000"
  MINIO_ACCESS_KEY: "smap"
  MINIO_SECRET_KEY: "hcmut2025"
