apiVersion: v1
kind: Secret
metadata:
  name: analytics-secrets
  namespace: smap
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://smap_owner:smap_owner%4021042004@172.16.19.114:5432/smap-project"